### ISSUE TITLE
Case-sensitive filenames

### ISSUE THREAD

**Issue by ghost** [bronydell/MGKE_Android_App#1]
Please note that on case-sensitive filesystems *.java files are expected to be named _exactly_ like the class, so r`app/src/main/java/ru/equestriadev/parsing/expiriments.java` should actually be `Expiriments.java`.

**Comment by bronydell** [comment]
I've made a new commit. Is everything okay now?

**Comment by ghost** [comment]
Yep, builds fine now. Thanks for the quick response!
